version: "2.2"

services:
  mongo:
    image: mongo:5.0.4
    container_name: sherlock_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db:rw
      - ./init:/docker-entrypoint-initdb.d

  search:
    image: node:latest
    container_name: sherlock_api
    working_dir: /app
    command: npm run dev
    links:
      - product
      - cache
    ports:
      - "8082:8080"
    environment:
      TARGET_HOST: "product:8080"
      SECRET: "hello world!"
      ACCESS_TOKEN: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiYWRtaW4iOnRydWUsImlhdCI6MTY1Mzg3NDAxM30.PDa_NPahbV8-xPlb4djOuQLr-xpMBvs8-LXiV-bzdZU"
    volumes:
      - .:/app

  product:
    image: wi4er/groot:0.13.3
    container_name: sherlock_product
    environment:
      DB_HOST: mongo
      DB_USER: product
      DB_PASSWORD: example
      DB_NAME: product
      CACHE_HOST: cache
    links:
      - mongo
      - cache
    ports:
      - "8081:8080"

  cache:
    image: redis:alpine
    container_name: sherlock_cache
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
