version: "2.2"

services:
  mongo:
    image: mongo:5.0.4
    container_name: charon_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db:rw
      - ./init:/docker-entrypoint-initdb.d

  search:
    image: node:latest
    container_name: search_api
    working_dir: /app
    command: npm start
    links:
      - product
      - cache
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  product:
    image: wi4er/groot:0.11.5
    container_name: product_api
    environment:
      DB_HOST: mongo
      DB_USER: user
      DB_PASSWORD: example
      DB_NAME: user
      CACHE_HOST: cache
    links:
      - mongo
      - cache
    ports:
      - "8081:8080"

  cache:
    image: redis:alpine
    container_name: charon_cache
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
